### ISSUE TITLE
Cannot create several tests

### ISSUE THREAD

**Issue by NinoLipartiia4ire** [near/workspaces-rs#44]
If you try running several separate tests with a sandboxed environment for the first time, at least one of them fails. 

See an example: https://github.com/NinoLipartiia4ire/workspaces-rs-example/commit/33a479d9f67c0fc6d2cdbc11510ccbc109f7a53e.
Both tests from this example should pass. But if you run them:
```bash
git clone https://github.com/NinoLipartiia4ire/workspaces-rs-example
cd workspaces-rs-example/tests-workspaces-rs && cargo test
```
Either one of them  fails:
```bash
test second_test ... ok
test first_test ... FAILED

failures:

---- first_test stdout ----
Starting up sandbox at localhost:24842
thread 'first_test' panicked at 'called `Result::unwrap()` on an `Err` value: Directory not empty (os error 66)', /Users/nino/.cargo/registry/src/github.com-1ecc6299db9ec823/workspaces-0.1.0/src/network/sandbox.rs:43:24
```
Or both tests fail:
```bash
test second_test ... FAILED
test first_test ... FAILED

failures:

---- second_test stdout ----
Starting up sandbox at localhost:22402
thread 'second_test' panicked at 'called `Result::unwrap()` on an `Err` value: /Users/nino/projects/issue-workspaces-rs/workspaces-rs-example/tests-workspaces-rs/target/debug/build/near-sandbox-utils-0a71fab0dd1ce1e6/out/near-sandbox-8b3f59a31cb9016b/near-sandbox is not executable', /Users/nino/.cargo/registry/src/github.com-1ecc6299db9ec823/workspaces-0.1.0/src/network/sandbox.rs:43:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- first_test stdout ----
Starting up sandbox at localhost:17497
thread 'first_test' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /Users/nino/.cargo/registry/src/github.com-1ecc6299db9ec823/workspaces-0.1.0/src/network/sandbox.rs:43:24

```

Running `cargo test` for the second time and later doesn't return any error, both tests pass. 

To reproduce this bug again: `cargo clean && cargo test`.

**Comment by ChaoticTempest** [comment]
I think I see the issue here. There was a race condition when installing the binary, so this should be fixed with this PR https://github.com/near/workspaces-rs/pull/46

**Comment by mikedotexe** [comment]
Given the last comment, I think I'll close this
